blackhane/Beauty

- 김동근/HTML/cart.html
- 김동근/HTML/css/cart.css
> 2023-03-02 HTML cart kdg

- 김보성/HTML/css/headfoot.css
- 김보성/HTML/js/main.js
- 김보성/HTML/list.html
> 2022/03/03 list.html 김보성

- 김동근/HTML/cart.html
- 김동근/HTML/css/cart.css
- 김동근/HTML/css/order.css
- 김동근/HTML/js/order.js
- 김동근/HTML/order.html
> 2023-03-06 HTML order kdg

- 강중현/html/member/login.html
- 강중현/html/member/register.html
1. register
- 약관 화면 구현
2. login
- 로그인 화면 구현
> 2023-03-06 강중현 login 화면 구현

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/java/kr/co/beauty/dao/MemberDAO.java
- beauty/src/main/java/kr/co/beauty/entity/MemberEntity.java
- beauty/src/main/java/kr/co/beauty/repository/MemberRepo.java
- beauty/src/main/java/kr/co/beauty/security/SecurityConfig.java
- beauty/src/main/java/kr/co/beauty/service/MemberService.java
- beauty/src/main/java/kr/co/beauty/vo/MemberVO.java
- beauty/src/main/java/kr/co/beauty/vo/TermsVO.java
- beauty/src/main/resources/mappers/member.xml
- beauty/src/main/resources/static/css/member/login.css
- beauty/src/main/resources/static/css/member/register.css
- beauty/src/main/resources/templates/_header.html
- beauty/src/main/resources/templates/member/login.html
- beauty/src/main/resources/templates/member/register.html
1. member
- 회원가입 구현 완료
- 로그인 문제 발생
> 2023-03-08 강중현

- beauty/src/main/java/kr/co/beauty/controller/Order1Controller.java
- beauty/src/main/java/kr/co/beauty/dao/Member1DAO.java
- beauty/src/main/java/kr/co/beauty/dao/MyshopDAO.java
- beauty/src/main/java/kr/co/beauty/dao/Order1DAO.java
- beauty/src/main/java/kr/co/beauty/service/MyshopService.java
- beauty/src/main/java/kr/co/beauty/service/Order1Service.java
- beauty/src/main/java/kr/co/beauty/utils/SessionManager.java
- beauty/src/main/resources/mappers/member1.xml
- beauty/src/main/resources/mappers/myshop.xml
- beauty/src/main/resources/mappers/order1.xml
> 2023-03-09 config kdg

- beauty/src/main/java/kr/co/beauty/controller/MainController.java
- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/java/kr/co/beauty/dao/MemberDAO.java
- beauty/src/main/java/kr/co/beauty/entity/MemberEntity.java
- beauty/src/main/java/kr/co/beauty/repository/MemberRepo.java
- beauty/src/main/java/kr/co/beauty/security/AccessDeniedHandlerImpl.java
- beauty/src/main/java/kr/co/beauty/security/AuthenticationEntryPointImpl.java
- beauty/src/main/java/kr/co/beauty/security/MyUserDetails.java
- beauty/src/main/java/kr/co/beauty/security/SecurityConfig.java
- beauty/src/main/java/kr/co/beauty/security/SecurityUserService.java
- beauty/src/main/java/kr/co/beauty/service/MemberService.java
- beauty/src/main/java/kr/co/beauty/vo/MemberVO.java
- beauty/src/main/resources/application.properties
- beauty/src/main/resources/mappers/member.xml
- beauty/src/main/resources/static/css/headfoot.css
- beauty/src/main/resources/static/css/member/login.css
- beauty/src/main/resources/static/css/member/register.css
- beauty/src/main/resources/templates/_header.html
- beauty/src/main/resources/templates/member/login.html
- beauty/src/main/resources/templates/member/register.html
1. member
- 로그인 구현 완료
- 자동로그인 구현 완료(테스트 필요)
> 2023-03-09 강중현

- beauty/src/main/java/kr/co/beauty/controller/Myshop1Controller.java
- beauty/src/main/java/kr/co/beauty/controller/Order1Controller.java
- beauty/src/main/java/kr/co/beauty/utils/SessionManager.java
- beauty/src/main/java/kr/co/beauty/vo/WishVO.java
- beauty/src/main/resources/static/css/order/cart.css
- beauty/src/main/resources/static/js/myshop/wishlist.js
- beauty/src/main/resources/static/js/order/cart.js
- beauty/src/main/resources/static/js/order/non-cart.js
- beauty/src/main/resources/templates/order/cart.html
> 2023-03-09 non-cart kdg

- beauty/src/main/java/kr/co/beauty/utils/SessionManager.java
- beauty/src/main/resources/static/css/order/cart.css
- beauty/src/main/resources/templates/order/cart.html
- 김동근/HTML/css/modal.css
- 김동근/HTML/modal.html
> 2023-03-10 cart modal kdg

- 김동근/HTML/css/modal.css
- 김동근/HTML/js/modal.js
- 김동근/HTML/modal.html
> 2023-03-12 modal kdg

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/java/kr/co/beauty/dao/MemberDAO.java
- beauty/src/main/java/kr/co/beauty/security/SecurityConfig.java
- beauty/src/main/java/kr/co/beauty/service/MemberService.java
- beauty/src/main/resources/mappers/member.xml
- beauty/src/main/resources/static/css/member/findId.css
- beauty/src/main/resources/templates/member/findId.html
- beauty/src/main/resources/templates/member/findIdResult.html
- beauty/src/main/resources/templates/member/login.html
> 2023-03-12 강중현

- beauty/src/main/java/kr/co/beauty/controller/MainController.java
- beauty/src/main/java/kr/co/beauty/controller/Myshop1Controller.java
- beauty/src/main/java/kr/co/beauty/controller/OrderController.java
- beauty/src/main/java/kr/co/beauty/utils/Pager.java
- beauty/src/main/java/kr/co/beauty/utils/SessionManager.java
- beauty/src/main/resources/static/js/cookieconsent.js
- beauty/src/main/resources/templates/error/errorCart.html
- beauty/src/main/resources/templates/index.html
- beauty/src/main/resources/templates/myshop/_mymenu.html
- 김동근/HTML/css/myorder.css
- 김동근/HTML/errorCart.html
- 김동근/HTML/myorder.html
자잘한 기능 수정
Pager 추가
myorder HTML 작업
> 2023-03-14 myorder kdg

- beauty/src/main/java/kr/co/beauty/controller/MainController.java
- beauty/src/main/resources/application.properties
- beauty/src/main/resources/static/css/order/cart.css
- 김동근/HTML/css/myPage.css
- 김동근/HTML/css/myhome.css
- 김동근/HTML/css/myorder.css
- 김동근/HTML/myhome.html
> 2023-03-15 myhome kdg

- beauty/src/main/java/kr/co/beauty/controller/Myshop1Controller.java
- beauty/src/main/resources/static/css/myshop/myPage.css
- beauty/src/main/resources/static/css/myshop/myhome.css
- beauty/src/main/resources/static/css/myshop/myorder.css
- beauty/src/main/resources/static/css/myshop/point.css
- beauty/src/main/resources/templates/myshop/_mymenu.html
- beauty/src/main/resources/templates/myshop/myhome.html
- beauty/src/main/resources/templates/myshop/myorder.html
- beauty/src/main/resources/templates/myshop/point.html
- 김동근/HTML/css/myPage.css
- 김동근/HTML/css/point.css
- 김동근/HTML/myPageTemp.html
- 김동근/HTML/myhome.html
- 김동근/HTML/myorder.html
- 김동근/HTML/point.html
- 김동근/HTML/wishlist.html
>  2023-03-16 point kdg

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/java/kr/co/beauty/security/AccessDeniedHandlerImpl.java
- beauty/src/main/java/kr/co/beauty/security/AuthFailureHandler.java
- beauty/src/main/java/kr/co/beauty/security/SecurityConfig.java
- beauty/src/main/resources/static/js/member/find.js
- beauty/src/main/resources/static/js/member/register.js
- beauty/src/main/resources/templates/member/find.html
- beauty/src/main/resources/templates/member/register.html
1. member
- 비밀번호 찾기 이메일 코드 전송
- 회원가입 약관 전체선택 구현
- 회원가입 주소 입력 구현
> 2023-03-16 강중현

- beauty/src/main/java/kr/co/beauty/controller/OrderController.java
- beauty/src/main/java/kr/co/beauty/dao/OrderDAO.java
- beauty/src/main/java/kr/co/beauty/service/OrderService.java
- beauty/src/main/java/kr/co/beauty/vo/CartVO.java
- beauty/src/main/java/kr/co/beauty/vo/ProductOptionVO.java
- beauty/src/main/resources/mappers/order.xml
- beauty/src/main/resources/static/css/order/cart.css
- beauty/src/main/resources/static/js/order/cart.js
- beauty/src/main/resources/static/js/order/modal.js
- beauty/src/main/resources/templates/order/cart.html
> 2023-03-19 cart kdg

- beauty/src/main/java/kr/co/beauty/controller/MainController.java
- beauty/src/main/java/kr/co/beauty/controller/OrderController.java
- beauty/src/main/java/kr/co/beauty/controller/ProductController.java
- beauty/src/main/java/kr/co/beauty/dao/OrderDAO.java
- beauty/src/main/java/kr/co/beauty/service/OrderService.java
- beauty/src/main/resources/application.properties
- beauty/src/main/resources/static/js/order/modal.js
- beauty/src/main/resources/static/js/order/non-order.js
- beauty/src/main/resources/static/js/order/order.js
- beauty/src/main/resources/static/js/order/ordercomplete.js
- beauty/src/main/resources/templates/order/_order.html
- beauty/src/main/resources/templates/order/cart.html
- beauty/src/main/resources/templates/order/non-orderform.html
- beauty/src/main/resources/templates/order/ordercomplete.html
- beauty/src/main/resources/templates/order/orderform.html
- beauty/src/main/resources/templates/product/view.html
> 2023-03-27 parkjinhwi

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/resources/application.properties
- beauty/src/main/resources/static/js/member/find.js
- beauty/src/main/resources/static/js/member/login.js
- beauty/src/main/resources/static/js/member/register.js
- beauty/src/main/resources/templates/member/find.html
- beauty/src/main/resources/templates/member/findIdResult.html
- beauty/src/main/resources/templates/member/findPwResult.html
- beauty/src/main/resources/templates/member/login.html
- beauty/src/main/resources/templates/member/register.html
> 2023-03-27 강중현

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/resources/static/js/member/find.js
- beauty/src/main/resources/templates/member/findPwResult.html
- beauty/src/main/resources/templates/member/login.html
> 2023-03-28 강중현

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/java/kr/co/beauty/vo/MemberVO.java
- beauty/src/main/resources/application.properties
- beauty/src/main/resources/static/js/member/find.js
- beauty/src/main/resources/static/js/member/findPwResult.js
- beauty/src/main/resources/static/js/member/joinNonOrder.js
- beauty/src/main/resources/static/js/member/login.js
- beauty/src/main/resources/templates/member/find.html
- beauty/src/main/resources/templates/member/findPwResult.html
- beauty/src/main/resources/templates/member/joinNonOrder.html
- beauty/src/main/resources/templates/member/login.html
1. vo
- 키, 몸무게 String > int로 수정
2. 비회원 주문 조회
- 작업중
> 2023-03-31 강중현

- beauty/src/main/java/kr/co/beauty/vo/MemberVO.java
- beauty/src/main/resources/mappers/member.xml
- beauty/src/main/resources/templates/myshop/_mymenu.html
> 2023-04-07 mypage kdg

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/java/kr/co/beauty/dao/MemberDAO.java
- beauty/src/main/java/kr/co/beauty/service/MemberService.java
- beauty/src/main/resources/mappers/member.xml
- beauty/src/main/resources/static/js/member/login.js
- beauty/src/main/resources/templates/member/login.html
1. 비회원 주문조회
- 비회원 주문조회 기능구현 완료
- 이름, 휴대폰, 주문번호 입력하여 주문조회 가능
- html 구현예정
> 2023-04-07 강중현

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/resources/static/js/member/login.js
- beauty/src/main/resources/templates/member/joinNonOrder.html
1. 비회원 주문조회
- joinNonOrder 페이지에 name, phone, 주문번호 조회 완료
2. html
- html은 myshop - myorder를 토대로 작업 예정
> 2023-04-10 강중현

- beauty/src/main/resources/templates/member/joinNonOrder.html
> 2023-04-11

- beauty/src/main/java/kr/co/beauty/controller/MyshopController.java
- beauty/src/main/java/kr/co/beauty/dao/MyshopDAO.java
- beauty/src/main/java/kr/co/beauty/service/MyshopService.java
- beauty/src/main/java/kr/co/beauty/vo/MyorderVO.java
- beauty/src/main/java/kr/co/beauty/vo/PointVO.java
- beauty/src/main/resources/mappers/myshop.xml
- beauty/src/main/resources/static/css/myshop/point.css
- beauty/src/main/resources/static/js/myshop/point.js
- beauty/src/main/resources/templates/myshop/point.html
> 2023-04-14 point kdg

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/java/kr/co/beauty/dao/MemberDAO.java
- beauty/src/main/java/kr/co/beauty/service/MemberService.java
- beauty/src/main/resources/templates/member/joinNonOrder.html
> 2023-04-14 강중현

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/java/kr/co/beauty/dao/MemberDAO.java
- beauty/src/main/java/kr/co/beauty/service/MemberService.java
- beauty/src/main/resources/mappers/member.xml
- beauty/src/main/resources/templates/member/joinNonOrder.html
> 2023-04-23 강중현

- beauty/src/main/java/kr/co/beauty/controller/MemberController.java
- beauty/src/main/java/kr/co/beauty/dao/MemberDAO.java
- beauty/src/main/java/kr/co/beauty/service/MemberService.java
- beauty/src/main/resources/mappers/member.xml
- beauty/src/main/resources/static/js/member/login.js
- beauty/src/main/resources/templates/member/joinNonOrder.html
1. 비회원 주문조회
- 주문 상품리스트 조회 가능
- 상품 페이지 넘버 미구현
> 2023-05-01 강중현
